### ISSUE TITLE
App crash on date click after navigating to other month

### ISSUE THREAD

**Issue by ashik991** [naishadhparmar/zcustomcalendar#2]
I get this error, "Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at org.naishadhparmar.zcustomcalendar.CustomCalendar$3.onClick(CustomCalendar.java:275)", when I navigate to the next month and click on a date.

**Comment by MagdalineMbugua** [comment]
Same here. I encounter the same issue:
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at org.naishadhparmar.zcustomcalendar.CustomCalendar$3.onClick(CustomCalendar.java:275)

**Comment by RealThomasMiles** [comment]
Same here

**Comment by shahina-almarwan** [comment]
Any solution for this?

**Comment by subhsis** [comment]
OnNavigationButtonClickedListener use whichbutton you click after that implement desired view that you want

**Comment by sohail756** [comment]
> OnNavigationButtonClickedListener use whichbutton you click after that implement desired view that you want

It would be very nice of you if you share this specific code.

**Comment by subhsis** [comment]
> 

 @Override
    public Map<Integer, Object>[] onNavigationButtonClicked(int whichButton, Calendar newMonth) {
        Map<Integer, Object>[] arr = new Map[2];
   
        if (whichButton==CustomCalendar.NEXT){
            //  view you want
        }if (whichButton==CustomCalendar.PREVIOUS){
                  //  view you want
        }
        return arr;
    }

--> call calendar instance to get the current month and implement on view as per your requirement.

**Comment by shamali1013** [comment]
> I get this error, "Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference at org.naishadhparmar.zcustomcalendar.CustomCalendar$3.onClick(CustomCalendar.java:275)", when I navigate to the next month and click on a date.

I encountered the same issue because i was calling this listener directly without using hashmap or simply i can say without defining properties and setting these to hashmap. I defined one property ("default") ,then this listener worked.

**Comment by Dyenal** [comment]
override fun onNavigationButtonClicked(
        whichButton: Int,
        newMonth: Calendar?
    ): Array<MutableMap<Int, Any>?> {
        val arr = arrayOfNulls<MutableMap<Int, Any>>(2)

        val currentMonth: Month = LocalDate.now().month
        val currentYear: Int = LocalDate.now().year
        if (newMonth != null) {
            if (newMonth.get(Calendar.MONTH)+1>currentMonth.value){
                customeCalander.setNavigationButtonEnabled(CustomCalendar.PREVIOUS,true)
            }else{

                if (newMonth.get(Calendar.YEAR)==currentYear)
                customeCalander.setNavigationButtonEnabled(CustomCalendar.PREVIOUS,false)
                else
                    customeCalander.setNavigationButtonEnabled(CustomCalendar.PREVIOUS,true)
            }



        }


        when (newMonth?.get(Calendar.MONTH)) {
            Calendar.JANUARY -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
                arr[1] = null // Optional: This is the map linking a date to its tag.
            }
            Calendar.FEBRUARY -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
                arr[1] = null // Optional: This is the map linking a date to its tag.
            }
            Calendar.MARCH -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
            }
            Calendar.APRIL -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
                arr[1] = null // Optional: This is the map linking a date to its tag.
            }
            Calendar.JULY -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
                arr[1] = null // Optional: This is the map linking a date to its tag.
            }
            Calendar.AUGUST -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
                arr[1] = null // Optional: This is the map linking a date to its tag.
            }
            Calendar.JUNE -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
            }
            Calendar.MAY -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
            }
            Calendar.SEPTEMBER -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
            }
            Calendar.OCTOBER -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
            }
            Calendar.NOVEMBER -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
            }
            Calendar.DECEMBER -> {
                arr[0] = HashMap<Int, Any>().apply {

                }
            }
        }



        return arr


    }
    
    try this code...

**Comment by lopo12123** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
brpandey, @TheoryOfNekomata, @c-soni, @omar-haris, @Jonmiller131313, @guantaiyangxi, @troizet, @lucasxsong, @Edisonhuxi, @MagnusCardell, @anjingxz, @shihp, @luthfianto, @nikolovay, @faizan-khan-iit, @Habu-Kagumba, @BigStar1994123, @Nubuck, @vperilla, @riyapannu7
